### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-obsidiancontrol-onyx#1]
The module `telnet-stream` that is required by this module is not allowed by the licensing used by companion. That is why we have created a replacement module for telnet in companion core.

Please remove the telnet-stream dependency, and instead use '../../telnet' like granadma2 module, or christie-wd, etc :)

**Comment by haakonnessjoen** [comment]
I have now done this myself in commit d16bf2036, 71046fbac2 and 1dfcdb357. But it needs testing befoe we pull it to companion.

**Comment by cgarwood** [comment]
Finally had a chance to test out a build with this update in it, I'm getting a recurring error popup when it tries to poll. I didn't get a chance to screenshot it on that machine, but I believe it was related to line 125 https://github.com/bitfocus/companion-module-obsidiancontrol-onyx/blob/master/index.js#L125 - saying that `self.write` wasn't a function. Looking at the code I think it should be `self.socket.write` - I'll try to get a dev environment spun back up on my home PC and see if that takes care of it

**Comment by cgarwood** [comment]
https://github.com/bitfocus/companion-module-obsidiancontrol-onyx/pull/4 fixes the error and feedback is working on my test system.
